[[headers]]
  for = "/*" # you can configure the correct paths here
  [headers.values]
    access-control-allow-origin = "https://casscosmology1.netlify.app" # see a list of allowed values here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin 
    Content-Security-Policy = "frame-ancestors https://casscosmology1.netlify.app"

